server {
  listen 80;
  root /var/www/portfolio/build;
  index index.html;                                                                                                       # Other config you desire (TLS, logging, etc)...
  location / {
    try_files $uri /index.html;
  }
}
